export const CONFIRM_RESET = "Are you sure you want to reset this list?"
export const CONFIRM_DELETE = "Are you sure you want to delete this item?"
export const MATCH_CONFIRM_RESET = "Are you sure you want to clear your match history?"
export const SKIP_MATCH_CONFIRM_CLEAR = "Are you sure you want to skip this match? The owner will charge you a fee!"
export const ADD_ITEM = "Type a name and hit enter"
